package tw.crestnetwork.rpg;

import com.example.crestrpg.database.RPGDatabase;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.OfflinePlayer;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.command.TabCompleter;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.SkullMeta;

import java.sql.*;
import java.util.*;

/** Persistent v2.8 guild core with commands and a chest-style player GUI. */
public final class RpgGuildManager implements Listener, CommandExecutor, TabCompleter {
    public record Guild(String id,String name,String tag,UUID owner,int level,double xp,double balance,String announcement) {}
    public record Member(UUID uuid,String name,String role,long joinedAt) {}
    private record GuildHolder(String guildId) implements InventoryHolder { public Inventory getInventory(){return null;} }
    private final CrestRpgPlugin plugin;
    private final RPGDatabase database;
    public RpgGuildManager(CrestRpgPlugin plugin,RPGDatabase database){this.plugin=plugin;this.database=database;}

    public synchronized Guild guild(UUID player){try(PreparedStatement statement=database.guildConnection().prepareStatement("SELECT g.* FROM crest_guilds g JOIN crest_guild_members m ON g.guild_id=m.guild_id WHERE m.uuid=?")){statement.setString(1,player.toString());try(ResultSet result=statement.executeQuery()){return result.next()?readGuild(result):null;}}catch(SQLException exception){plugin.getLogger().warning("讀取工會失敗："+exception.getMessage());return null;}}
    public synchronized List<Member> members(String guildId){List<Member> values=new ArrayList<>();try(PreparedStatement statement=database.guildConnection().prepareStatement("SELECT * FROM crest_guild_members WHERE guild_id=? ORDER BY CASE role WHEN 'OWNER' THEN 0 WHEN 'OFFICER' THEN 1 ELSE 2 END, joined_at")){statement.setString(1,guildId);try(ResultSet result=statement.executeQuery()){while(result.next())values.add(new Member(UUID.fromString(result.getString("uuid")),result.getString("player_name"),result.getString("role"),result.getLong("joined_at")));}}catch(SQLException exception){plugin.getLogger().warning("讀取工會成員失敗："+exception.getMessage());}return List.copyOf(values);}
    private synchronized String role(UUID player){try(PreparedStatement statement=database.guildConnection().prepareStatement("SELECT role FROM crest_guild_members WHERE uuid=?")){statement.setString(1,player.toString());try(ResultSet result=statement.executeQuery()){return result.next()?result.getString(1):null;}}catch(SQLException ignored){return null;}}

    private synchronized String create(Player player,String name,String tag){if(guild(player.getUniqueId())!=null)return "你已經加入工會。";if(!name.matches("[\\p{L}0-9_]{2,32}")||!tag.matches("[\\p{L}0-9]{2,8}"))return "名稱需 2-32 字，標籤需 2-8 字，且不可包含特殊符號。";double cost=setting("creation_cost",0);if(cost>0&&!VaultEconomyBridge.withdraw(player,cost))return "建立工會需要 "+cost+"，你的餘額不足。";String id=UUID.randomUUID().toString();try{Connection connection=database.guildConnection();try(PreparedStatement guild=connection.prepareStatement("INSERT INTO crest_guilds(guild_id,name,tag,owner_uuid,created_at) VALUES(?,?,?,?,?)");PreparedStatement member=connection.prepareStatement("INSERT INTO crest_guild_members(guild_id,uuid,player_name,role,joined_at) VALUES(?,?,?,?,?)")){long now=System.currentTimeMillis();guild.setString(1,id);guild.setString(2,name);guild.setString(3,tag.toUpperCase(Locale.ROOT));guild.setString(4,player.getUniqueId().toString());guild.setLong(5,now);guild.executeUpdate();member.setString(1,id);member.setString(2,player.getUniqueId().toString());member.setString(3,player.getName());member.setString(4,"OWNER");member.setLong(5,now);member.executeUpdate();return "已建立工會「"+name+"」。";}}catch(SQLException exception){if(cost>0)VaultEconomyBridge.deposit(player,cost);return "建立失敗，名稱或標籤可能已被使用。";}}
    private synchronized String invite(Player actor,Player target){Guild guild=guild(actor.getUniqueId());if(guild==null)return "你尚未加入工會。";String role=role(actor.getUniqueId());if(!"OWNER".equals(role)&&!"OFFICER".equals(role))return "只有會長或幹部可以邀請。";if(guild(target.getUniqueId())!=null)return "該玩家已加入工會。";int minutes=Math.max(1,(int)setting("invite_expiry_minutes",5));try(PreparedStatement delete=database.guildConnection().prepareStatement("DELETE FROM crest_guild_invites WHERE guild_id=? AND uuid=?");PreparedStatement insert=database.guildConnection().prepareStatement("INSERT INTO crest_guild_invites(guild_id,uuid,invited_by,expires_at) VALUES(?,?,?,?)")){delete.setString(1,guild.id());delete.setString(2,target.getUniqueId().toString());delete.executeUpdate();insert.setString(1,guild.id());insert.setString(2,target.getUniqueId().toString());insert.setString(3,actor.getUniqueId().toString());insert.setLong(4,System.currentTimeMillis()+minutes*60_000L);insert.executeUpdate();target.sendMessage(Component.text("你收到「"+guild.name()+"」的工會邀請，"+minutes+" 分鐘內輸入 /guild accept。",NamedTextColor.AQUA));return "已邀請 "+target.getName()+"。";}catch(SQLException exception){return "邀請失敗："+exception.getMessage();}}
    private synchronized String accept(Player player){if(guild(player.getUniqueId())!=null)return "你已經加入工會。";try(PreparedStatement find=database.guildConnection().prepareStatement("SELECT guild_id FROM crest_guild_invites WHERE uuid=? AND expires_at>=? ORDER BY expires_at DESC")){find.setString(1,player.getUniqueId().toString());find.setLong(2,System.currentTimeMillis());try(ResultSet result=find.executeQuery()){if(!result.next())return "目前沒有有效的工會邀請。";String id=result.getString(1);if(members(id).size()>=Math.max(1,(int)setting("max_members",50)))return "這個工會的成員人數已達上限。";try(PreparedStatement insert=database.guildConnection().prepareStatement("INSERT INTO crest_guild_members(guild_id,uuid,player_name,role,joined_at) VALUES(?,?,?,?,?)");PreparedStatement clear=database.guildConnection().prepareStatement("DELETE FROM crest_guild_invites WHERE uuid=?")){insert.setString(1,id);insert.setString(2,player.getUniqueId().toString());insert.setString(3,player.getName());insert.setString(4,"MEMBER");insert.setLong(5,System.currentTimeMillis());insert.executeUpdate();clear.setString(1,player.getUniqueId().toString());clear.executeUpdate();return "已加入工會。";}}}catch(SQLException exception){return "加入失敗："+exception.getMessage();}}
    private synchronized String leave(Player player){Guild guild=guild(player.getUniqueId());if(guild==null)return "你尚未加入工會。";if(guild.owner().equals(player.getUniqueId()))return "會長必須先解散工會，不能直接退出。";try(PreparedStatement statement=database.guildConnection().prepareStatement("DELETE FROM crest_guild_members WHERE uuid=?")){statement.setString(1,player.getUniqueId().toString());statement.executeUpdate();return "已退出工會。";}catch(SQLException exception){return "退出失敗。";}}
    private synchronized String disband(Player player){Guild guild=guild(player.getUniqueId());if(guild==null||!guild.owner().equals(player.getUniqueId()))return "只有會長可以解散工會。";try(PreparedStatement members=database.guildConnection().prepareStatement("DELETE FROM crest_guild_members WHERE guild_id=?");PreparedStatement invites=database.guildConnection().prepareStatement("DELETE FROM crest_guild_invites WHERE guild_id=?");PreparedStatement root=database.guildConnection().prepareStatement("DELETE FROM crest_guilds WHERE guild_id=?")){for(PreparedStatement statement:List.of(members,invites,root)){statement.setString(1,guild.id());statement.executeUpdate();}return "工會已解散。";}catch(SQLException exception){return "解散失敗。";}}
    private synchronized String rank(Player actor,OfflinePlayer target,boolean promote){Guild guild=guild(actor.getUniqueId());if(guild==null||!guild.owner().equals(actor.getUniqueId()))return "只有會長可以調整階級。";if(target.getUniqueId().equals(actor.getUniqueId()))return "不能調整自己的會長階級。";try(PreparedStatement statement=database.guildConnection().prepareStatement("UPDATE crest_guild_members SET role=? WHERE guild_id=? AND uuid=?")){statement.setString(1,promote?"OFFICER":"MEMBER");statement.setString(2,guild.id());statement.setString(3,target.getUniqueId().toString());return statement.executeUpdate()>0?"已將 "+target.getName()+" 設為 "+(promote?"幹部":"成員")+"。":"該玩家不在你的工會。";}catch(SQLException exception){return "階級更新失敗。";}}
    private synchronized String donate(Player player,double amount){Guild guild=guild(player.getUniqueId());if(guild==null)return "你尚未加入工會。";if(amount<=0||!Double.isFinite(amount))return "捐獻金額必須大於 0。";if(!VaultEconomyBridge.withdraw(player,amount))return "餘額不足，或伺服器尚未安裝 Vault 經濟系統。";double gained=amount*setting("donation_xp_ratio",.1);try(PreparedStatement statement=database.guildConnection().prepareStatement("UPDATE crest_guilds SET balance=balance+?, xp=xp+? WHERE guild_id=?")){statement.setDouble(1,amount);statement.setDouble(2,gained);statement.setString(3,guild.id());statement.executeUpdate();Guild updated=guild(player.getUniqueId());int level=updated==null?1:1+(int)Math.floor(Math.sqrt(updated.xp()/1000.0));try(PreparedStatement levelUpdate=database.guildConnection().prepareStatement("UPDATE crest_guilds SET level=? WHERE guild_id=?")){levelUpdate.setInt(1,Math.max(1,level));levelUpdate.setString(2,guild.id());levelUpdate.executeUpdate();}return "已向工會捐獻 "+amount+"，獲得 "+gained+" 工會經驗。";}catch(SQLException exception){VaultEconomyBridge.deposit(player,amount);return "捐獻寫入失敗，款項已退回。";}}
    private synchronized String announcement(Player player,String text){Guild guild=guild(player.getUniqueId());String role=role(player.getUniqueId());if(guild==null||(!"OWNER".equals(role)&&!"OFFICER".equals(role)))return "只有會長或幹部可以修改公告。";if(text.length()>512)return "公告不可超過 512 字。";try(PreparedStatement statement=database.guildConnection().prepareStatement("UPDATE crest_guilds SET announcement=? WHERE guild_id=?")){statement.setString(1,text);statement.setString(2,guild.id());statement.executeUpdate();return "工會公告已更新。";}catch(SQLException exception){return "公告更新失敗。";}}

    public void open(Player player){Guild guild=guild(player.getUniqueId());if(guild==null){Inventory inventory=Bukkit.createInventory(new GuildHolder(""),27,Component.text("尚未加入工會",NamedTextColor.DARK_AQUA));inventory.setItem(13,item(Material.OAK_SIGN,"建立或加入工會",List.of("/guild create <名稱> <標籤>","/guild accept 接受邀請")));player.openInventory(inventory);return;}Inventory inventory=Bukkit.createInventory(new GuildHolder(guild.id()),54,Component.text("["+guild.tag()+"] "+guild.name(),NamedTextColor.DARK_AQUA));inventory.setItem(4,item(Material.BEACON,guild.name(),List.of("等級："+guild.level(),"經驗："+guild.xp(),"資金："+guild.balance(),"公告："+(guild.announcement().isBlank()?"尚未設定":guild.announcement()))));int slot=10;for(Member member:members(guild.id())){if(slot>=44)break;ItemStack head=new ItemStack(Material.PLAYER_HEAD);SkullMeta meta=(SkullMeta)head.getItemMeta();meta.setOwningPlayer(Bukkit.getOfflinePlayer(member.uuid()));meta.displayName(Component.text(member.name(),NamedTextColor.GOLD));meta.lore(List.of(Component.text(roleName(member.role()),NamedTextColor.GRAY)));head.setItemMeta(meta);inventory.setItem(slot++,head);if(slot%9==8)slot+=2;}inventory.setItem(46,item(Material.EMERALD,"捐獻資金",List.of("使用 /guild donate <金額>")));inventory.setItem(48,item(Material.PAPER,"修改公告",List.of("使用 /guild announcement <內容>")));inventory.setItem(50,item(Material.BELL,"邀請玩家",List.of("使用 /guild invite <玩家>")));inventory.setItem(53,item(Material.BARRIER,"關閉",List.of()));player.openInventory(inventory);}
    @EventHandler public void click(InventoryClickEvent event){if(!(event.getInventory().getHolder() instanceof GuildHolder)||!(event.getWhoClicked() instanceof Player player))return;event.setCancelled(true);if(event.getRawSlot()==53)player.closeInventory();if(event.getRawSlot()==46){player.closeInventory();player.sendMessage(Component.text("用法：/guild donate <金額>",NamedTextColor.YELLOW));}}
    @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){if(!(sender instanceof Player player)){sender.sendMessage("此指令僅供玩家使用。");return true;}if(args.length==0||args[0].equalsIgnoreCase("gui")){open(player);return true;}String result=switch(args[0].toLowerCase(Locale.ROOT)){case "create"->args.length>=3?create(player,args[1],args[2]):"用法：/guild create <名稱> <標籤>";case "invite"->args.length>=2&&Bukkit.getPlayerExact(args[1])!=null?invite(player,Objects.requireNonNull(Bukkit.getPlayerExact(args[1]))):"找不到在線玩家。";case "accept"->accept(player);case "leave"->leave(player);case "disband"->disband(player);case "promote","demote"->args.length>=2?rank(player,Bukkit.getOfflinePlayer(args[1]),args[0].equalsIgnoreCase("promote")):"請輸入玩家名稱。";case "donate"->args.length>=2?donate(player,number(args[1])):"用法：/guild donate <金額>";case "announcement"->args.length>=2?announcement(player,String.join(" ",Arrays.copyOfRange(args,1,args.length))):"請輸入公告內容。";default->"用法：/guild create|invite|accept|leave|disband|promote|demote|donate|announcement|gui";};player.sendMessage(Component.text(result,result.contains("失敗")||result.contains("不能")||result.contains("只有")?NamedTextColor.RED:NamedTextColor.AQUA));return true;}
    @Override public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){if(args.length==1)return List.of("gui","create","invite","accept","leave","disband","promote","demote","donate","announcement").stream().filter(value->value.startsWith(args[0].toLowerCase(Locale.ROOT))).toList();if(args.length==2&&List.of("invite","promote","demote").contains(args[0].toLowerCase(Locale.ROOT)))return Bukkit.getOnlinePlayers().stream().map(Player::getName).toList();return List.of();}
    private static Guild readGuild(ResultSet result)throws SQLException{return new Guild(result.getString("guild_id"),result.getString("name"),result.getString("tag"),UUID.fromString(result.getString("owner_uuid")),result.getInt("level"),result.getDouble("xp"),result.getDouble("balance"),result.getString("announcement"));}
    private double setting(String key,double fallback){var value=plugin.getDraftManager().getDraft("guild-settings","main");return value!=null&&value.has(key)?value.get(key).getAsDouble():fallback;}
    private static double number(String raw){try{return Double.parseDouble(raw);}catch(NumberFormatException ignored){return -1;}}
    private static String roleName(String role){return switch(role){case "OWNER"->"會長";case "OFFICER"->"幹部";default->"成員";};}
    private static ItemStack item(Material material,String name,List<String> lore){ItemStack item=new ItemStack(material);ItemMeta meta=item.getItemMeta();meta.displayName(Component.text(name,NamedTextColor.GOLD));meta.lore(lore.stream().map(line->Component.text(line,NamedTextColor.GRAY)).toList());item.setItemMeta(meta);return item;}
}
